version: "3.9"

services:
  api:
    build: .
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      TOKEN_EXPIRE_SECONDS: ${TOKEN_EXPIRE_SECONDS}
    ports:
      - "5000:5000"
