version: "3.9"

services:
  api:
    build: .
    restart: always
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      FACEBOOK_APP_ID: ${FACEBOOK_APP_ID}
      TOKEN_EXPIRE_SECONDS: ${TOKEN_EXPIRE_SECONDS}
    ports:
      - "8000:8000"
